<<: *{model.transformer}
model:
  _target_: anemoi.models.models.encoder_processor_decoder.AnemoiModelEncProcDecEns

inject_noise: False

noise_injector:
  _target_: anemoi.models.layers.noise.StandardGaussianNoiseInjector
  _convert_: all
  noise_channels_dim: 4
  noise_mlp_hidden_dim: 32
