model:
  _target_: anemoi.models.models.reconstruction.AnemoiBetaVAE
  _partial_: True

activation: GELU
num_channels: 256
no_latent_levels: 1 # Hierarchical VAE setting
no_z_samples: 1 # No of Z samples



encoder:
 num_channels: ${model.num_channels}
 freeze_parameters: False
 mapper:
   _target_: anemoi.models.layers.mapper.GraphTransformerForwardMapper
    _convert_: all
    trainable_size: ${model.trainable_parameters.data2hidden}
    activation: ${model.activation}
    num_chunks: 1
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 16 # GraphTransformer or Transformer only
  processor:
    _target_: anemoi.models.layers.processor.TransformerProcessor
    _convert_: all
    activation: ${model.activation}
    num_layers: 2
    num_chunks: 2
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 16 # GraphTransformer or Transformer only
    window_size: 256
    dropout_p: 0.00


decoder:
 num_channels: ${model.num_channels}
 freeze_parameters: False
 mapper:
   _target_: anemoi.models.layers.mapper.GraphTransformerBackwardMapper
    _convert_: all
    trainable_size: ${model.trainable_parameters.hidden2data}
    activation: ${model.activation}
    num_chunks: 1
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 16 # GraphTransformer or Transformer only
 processor:
    _target_: anemoi.models.layers.processor.TransformerProcessor
    _convert_: all
    activation: ${model.activation}
    num_layers: 2
    num_chunks: 2
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 16 # GraphTransformer or Transformer only
    window_size: 256
    dropout_p: 0.00


trainable_parameters:
  data: 8
  hidden: 8
  data2hidden: 8
  hidden2data: 8


attributes:
  edges:
  - edge_length
  - edge_dirs
  nodes: []

node_loss_weight: area_weight
