dataset: ???
graph: ???
checkpoint:
  every_n_epochs: anemoi-by_epoch-epoch_{epoch:03d}-step_{step:06d}
  every_n_train_steps: anemoi-by_step-epoch_{epoch:03d}-step_{step:06d}
  every_n_minutes: anemoi-by_time-epoch_{epoch:03d}-step_{step:06d}
warm_start: null
