defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- hardware: example
- graph: hierarchical_3level
- model: graphtransformer
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

model:
  model:
    _target_: anemoi.models.models.AnemoiModelEncProcDecHierarchical
  enable_hierarchical_level_processing: True
  level_process_num_layers: 2
