prefetch_factor: 1

num_workers:
  training: 1
  validation: 1
batch_size:
  training: 1
  validation: 1

# ============
# Default effective batch_size for training is 16
# For the o96 resolution, default per-gpu batch_size is 2 (8 gpus required)
# The global lr is calculated as:
# global_lr = local_lr * num_gpus_per_node * num_nodes / gpus_per_model
# Assuming a constant effective batch_size, any change in the per_gpu batch_size
# should come with a rescaling of the local_lr to keep a constant global_lr
# ============

# runs only N training batches [N = integer | null]
# if null then we run through all the batches
limit_batches:
  training: 50 # null
  validation: 20 # null
  test: 20
  predict: 20

# ============
# Dataloader definitions
# These follow the anemoi-datasets patterns
# You can make these as complicated for merging as you like
# See https://anemoi-datasets.readthedocs.io
# ============

#dataset:
#  observations: # for now observations must be on top level, will be removed
#    multiple: # automatically pad the datasets with the min and max dates, will be renamed to zip
#      - dataset: observations-ea-ofb-0001-2004-2023-combined-metar-v1
#        frequency: 6h # this may become optional
#        rename_prefix: metar_ # this may become optional
#        is_observations: true # will disappear
#        select:
#          - metar_sin_latitude
#          - metar_cos_latitude
#          - metar_sin_longitude
#          - metar_cos_longitude
#          - metar_t2m_0
#      - dataset: aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6

# dataset_test2:
#   observations:
#     multiple:
#       - dataset: observations-ea-ofb-0001-2004-2023-combined-metar-v1
#         frequency: 6h # this may become optional
#         rename_prefix: metar_ # this may become optional
#         is_observations: true # will disappear
#         select:
#           # forcings
#           - metar_sin_latitude
#           - metar_cos_latitude
#           - metar_sin_longitude
#           - metar_cos_longitude
#           - metar_stalt
#           - metar_lsm
#           - metar_cos_sza
#           - metar_sin_julian_day
#           - metar_cos_julian_day
#           - metar_sin_local_time
#           - metar_cos_local_time
#           # obs data
#           - metar_t2m_0
#           - metar_u10m_0
#           - metar_t2m_0
#           # - metar_rh2m_0
#           # - metar_ps_0
dataset:
  observations: # for now observations must be on top level, will be removed
    _start: 2004-06
    _end: 2004-07
    #_end: 2023
    #_end: 2005-01-05
    multiple: # automatically pad the datasets with the min and max dates, will be renamed to zip
      era5:
        dataset: aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6
      metar:
        dataset: observations-ea-ofb-0001-2004-2023-combined-metar-v1
        frequency: 6h # this may become optional
        rename_prefix: metar_ # this may become optional
        is_observations: true # will disappear
        select:
          # forcings
          - sin_latitude
          - cos_latitude
          - sin_longitude
          - cos_longitude
          - stalt
          - lsm
          - cos_sza
          - sin_julian_day
          - cos_julian_day
          - sin_local_time
          - cos_local_time
          # obs data
          - t2m_0
          - u10m_0
          # - rh2m_0
          # - ps_0
      noaa-atms:
        dataset: observations-ea-ofb-0001-2018-2023-noaa-20-atms-radiances-v1
        frequency: 6h # this may become optional
        rename_prefix: noaa_20_atms_ # this may become optional
        is_observations: true # will desappear
        select:
          # forcings
          - sin_latitude
          - cos_latitude
          - sin_longitude
          - cos_longitude
          - sin_julian_day
          - cos_julian_day
          - sin_local_time
          - cos_local_time
          - cos_sza
          - cos_vza
          # obs data
          - rawbt_1
          - rawbt_2
          - rawbt_3
          - rawbt_4
          - rawbt_5
          - rawbt_6
          - rawbt_7
          - rawbt_8
          - rawbt_9
          - rawbt_10
          - rawbt_11
          - rawbt_12
          - rawbt_13
          - rawbt_14
          - rawbt_15
          - rawbt_16
          - rawbt_17
          - rawbt_18
          - rawbt_19
          - rawbt_20
          - rawbt_21
          - rawbt_22
    ##########################################################
    # TODO: ADD FUNCTIONALITY TO SPLIT THE TENSORS differently
    ##########################################################

training: ${dataloader.dataset}
validation: ${dataloader.dataset}

# features that are not part of the forecast state
# but are used as forcing to generate the forecast state
forcing:
  # metar
  - metar_sin_latitude
  - metar_cos_latitude
  - metar_cos_longitude
  - metar_sin_longitude
  - metar_stalt
  - metar_lsm
  - metar_cos_sza
  - metar_sin_julian_day
  - metar_cos_julian_day
  - metar_sin_local_time
  - metar_cos_local_time
  # noaa_20_atms
  - noaa_20_atms_cos_latitude
  - noaa_20_atms_sin_latitude
  - noaa_20_atms_cos_longitude
  - noaa_20_atms_sin_longitude
  - noaa_20_atms_sin_julian_day
  - noaa_20_atms_cos_julian_day
  - noaa_20_atms_sin_local_time
  - noaa_20_atms_cos_local_time
  - noaa_20_atms_cos_sza
  - noaa_20_atms_cos_vza
  # era5
  - cos_latitude
  - cos_longitude
  - sin_latitude
  - sin_longitude
  - cos_julian_day
  - cos_local_time
  - sin_julian_day
  - sin_local_time
  - insolation
  - lsm
  - sdor
  - slor
  - z
# features that are only part of the forecast state
# but are not used as the input to the model
diagnostic:
  - tp
  - cp
remapped: null
