<<: *{training.default}

lightning_module:
  _target_: anemoi.training.lightning_module.forecasting.LightningModuleDeterministic

# length of the "rollout" window (see Keisler's paper)
rollout:
  start: 1
  # increase rollout every n epochs
  epoch_increment: 0
  # maximum rollout to use
  max: 1