---
    name: Label Checker
    on:
      pull_request:
        types:
          - opened
          - synchronize
          - reopened
          - labeled
          - unlabeled
        branches:
          - develop

    jobs:

      check_labels:
        name: Check labels
        runs-on: ubuntu-latest
        steps:
          - uses: docker://agilepathway/pull-request-label-checker:latest
            with:
              any_of: ATS approved, No approval needed
              none_of: invalid,wontfix,duplicate,question
              repo_token: ${{ secrets.GITHUB_TOKEN }}
